#!/bin/bash
make clean

if [ -z "$AVR_FREQ" ]
then
  AVR_FREQ=8000000L
fi

if [ -z "$BAUD_RATE" ]
then
  BAUD_RATE=57600
fi

if [ -z "$USINGMAKEFILES" ]
then 
  USINGMAKEFILES="Makefile.atmega8 Makefile.atmega640-1280-1281-2560-2561 Makefile.atmegaxx4-16-31 Makefile.attinyx5 Makefile.attinyx4"
fi

if [ -z "$OSCCAL_PROGMEM" ]
then
  OSCCAL_PROGMEM="1"
fi

export AVR_FREQ
export BAUD_RATE
export OSCCAL_PROGMEM

for chip in $(cat $USINGMAKEFILES | grep -oP "^([A-Za-z0-9_]+)(?:\:)" | grep -v isp | sort | uniq | sed s/://)
do
  echo -n "Building $chip with CPU $AVR_FREQ and $BAUD_RATE BAUD ... "
  
  if ! ( make $chip 2>&1 ) >$chip.build_log
  then
    echo "FAILED, SEE: $chip.build_log"
    exit
  else    
    echo -n "OK, SIZE: "
    avr-size optiboot_${chip}_${AVR_FREQ}_${BAUD_RATE}.hex | grep -oP "[1-9][0-9]+" | head -1
  fi
done

ls *hex
